### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by zenko-kyubiko** [redbow26/Furcelieux-server#1]
# Description:

## Day:
During the day every players can use the chat to debate about who kill during the vote.
## Night:
During the night only the werewolf will be able to use the chat and they will not see the name of the player that send the message.

# Todo:
- [x] Receive message
- [x] Broadcast to every player
- [x] Broadcast to specific player (like werewolf)
- [x] Add color
- [x] Show/Hide username
